feat: entity 재설정 #12
KooK-PaP/kook-Pap-Server pull request #13
Opened 2023-09-14 08:45 UTC by Ryooon2

# PR Summary
- close #12 

## PR Detail Description
주요 작업:
- Bucket enity 작성
- Order entity 작성
- Restaurant의 time 칼럼을 Operation Column으로 따로 작성
- Member entity에 address 칼럼 추가
## Screenshots (Optional)
기존의 ERD:
https://user-images.githubusercontent.com/138233569/259628045-b802268a-4d6d-43ee-b65b-32ffc1914a76.png
위 ERD에서 비지니스 로직에 음식을 주문 로직을 추가하기 위하여 아래와 같이 변경되었습니다.

https://user-images.githubusercontent.com/138233569/267866020-60061ee1-16c4-49ec-8155-a000af68d970.png
- Order: 주문한 음식을 표현하는 엔티티
- Bucket: 주문에 대한 명세표를 표현하는 엔티티
- Operation: 현재 영업중인 가게를 조회하는데 수월하도록, 기존의 time column을 대체하는 엔티티를 새로 작성
- 비지니스 로직에, 음식 주문 로직이 추가되었기 때문에 member 테이블에 address Column이 추가되었습니다.

2023-09-14 08:52 UTC, dl-00-e8 requested changes
Member의 address와 Restaurant의 location 칼럼은 같은 역할을 하지만, 다른 네이밍을 사용하고 있는 것  같습니다. 이를 동일한 것으로 맞추어 사용하는 것은 어떨까요?

2023-09-14 08:52 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/entity/Member.java
address를 검증하기 위해 정규표현식을 도입하는 건 어떤가요?

2023-09-14 08:52 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/order/entity/OrderState.java
각 state 대해서 주석을 달아서 추후 확인시 명확하게 하면 더 좋을 것 같네요

2023-09-14 08:52 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/restaurant/entity/Restaurant.java
location의 주소는 정규표현식을 도입하는 건 어떤가요?

2023-09-14 09:54 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/entity/Member.java
해당 부분은 저도 생각하지 못했던것 같네요.
추후 address에 대해서는 정규표현식을 도입하겠지만, entity에 설정하는 것 보다는, dto에 설정하는 것이 좀 더 나을 것 같네요.
DB에서 발생하는 Exception을 핸들링하는 것 보다는, Server에서 검증하는 것이 좀 더 이점이 커 보입니다!

2023-09-14 09:55 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/order/entity/OrderState.java
넵. 주석으로 column과, state에 대해서 설명을 작성하였습니다.

2023-09-14 10:00 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/entity/Member.java
또한 이정진님 말씀대로, address와 location이 같은 역할을 수행하지만 네이밍이 다르다는 점을 미처 확인하지 못했습니다.
지적해주셔서 감사합니다. 
주소 관련 column들은 address로 통일하였습니다.

2023-09-16 02:41 UTC, Cfctor9 commented on src/main/java/com/KooKPaP/server/domain/member/entity/Member.java
가게 테이블에 가게 이름이 없어도 될까요?

2023-09-16 12:20 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/entity/Member.java
제가 지금 로그인 관련해서 너무 많은 로직을 미리 작성한 관계로 혹시 다음 PR에서 추가해도 될까요?

2023-09-17 05:12 UTC, Cfctor9 approved these changes

2023-09-17 12:00 UTC, dl-00-e8 approved these changes
말씀드렸던 부분과 추가적으로 고민했던 부분들 변경되었던 것들 다 확인했습니다. 수고 많으셨습니다.

2023-09-17 12:00 UTC, merged