Feat: auth 도메인 관련 로직 작성
KooK-PaP/kook-Pap-Server pull request #18
Opened 2023-09-18 07:50 UTC by Ryooon2

# PR Summary
- close #14 
- close #15 
- close #16 
- close #17 

## PR Detail Description

auth와 관련된 로직들을 일반 로그인 관련, 카카오 로그인 관련, 공통 사항 이렇게 3개로 나누어서 작성하였습니다.

일반 로그인에 관련된 로직들은 GeneralAuthService에
카카오 로그인에 관련된 로직들은 KakaoAuthService에,
공통 사항은 CommonAuthService에 작성하였습니다.

**GeneralAuthService**:
일반 로그인에서 필요한 사항 다음 4가지로 구분할 수 있겠습니다.
- **인증 메일 전송** : 사용자가 이메일(정규 표현식 도입)을 POST로 전송하면, DB에 해당 이메일로 이미 회원가입을 한 회원이 있는지 검사한 후, JavaMailSender를 이용해 6자리 랜덤 인증 코드를 전송합니다. 인증 코드는 redis에 <이메일, 인증코드>로 30분간 저장됩니다.
- **인증 코드 검증**: 사용자가 이메일과 인증코드를 POST로 전송하면, redis에 저장된 인증코드와 비교하여 해당 인증코드가 옳을 경우, <이메일, "verified">로 이메일이 인증되었다는 상태를 redis에 30분간 저장합니다.
- **회원 가입**: 사용자가 회원가입에 필요한 정보들(이메일과 주소는 정규표현식 도입)을 POST로 전송하면, 해당 이메일이 redis에 인증된 상태로 저장되어있는지 검사하고, DB에 저장하여 회원가입을 수행합니다. 이때 비밀번호는 PasswordEncoder로 단방향 암호화로 저장합니다.
- **로그인**: 이메일과 비밀번호로 POST 요청시, DB에 저장된 비밀번호와 비교하여 요청이 옳바른지 검증합니다. 이후 JwtTokenProvider를 통해 JwtTokenDto를 생성하여 반환합니다.

**KakaoAuthService**:
해당 클래스는 카카오 로그인에 필요한 메서드들을 작성하였으며, OAuth2Login 보다는 API 직접 호출로 작성되었습니다.
로그아웃시 리소스 서버에 OauthToken을 만료요청을 하기에는 API 직접 호출이 더 적절하다고 생각했기 때문입니다.
KakaoAuthService에 작성되어 있는 메서드들은 다음과 같습니다.
- **OauthToken 받아오기**: 사용자의 카카오 로그인 정보를 토대로 만들어진 인가 code를 카카오 서버에 전송하여 OauthToken을 받아옵니다. 해당 OauthToken은 프로필 정보에 접근하는 등, 사용자의 리소스에 접근하기 위해 필요합니다.
- **프로필 정보 받아오기**: 위에서 받은 OauthToken으로 사용자 정보를 리소스 서버로부터 받아옵니다.
- **회원가입 및 JwtTokenDto 반환**: 사용자 프로필의 email로 DB에 저장된 회원이 있는지 확인합니다. 만약 존재할 경우, 해당 회원의 type이 KAKAO인지 검사합니다. 만일 KAKAO가 아닐 경우, 중복되는 email로 회원가입을 시도하는 것이기 때문에 Exception을 던집니다. type이 KAKAO가 맞을 경우, 이미 회원가입을 진행한 회원이므로 JwtTokenDto를 생성하여 반환합니다. DB에 저장된 회원이 없을 경우, 신규회원이므로 DB에 save하여 회원가입을 진행한 후, JwtTokenDto를 생성하여 반환합니다. 또한 로그아웃때 OauthToken을 사용해야 하므로, redis에 <memberId, OauthToken> 으로 저장합니다.
- **로그아웃**: redis에서 memberId를 키값으로 저장된 OauthToken을 찾고, 해당 토큰으로 리소스 서버에게 로그아웃을 요청합니다. 이 로그아웃은 발급받은 엑세스 토큰을 만료 처리하는 것 입니다. [(상세 설명)](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#logout)
- **OauthToken 만료 여부 검사 및 Refresh**: 해당 메서드는 리소스 서버의 API를 직접호출하여 OauthToken이 만료되었는지 검사하고, 만료되었다면 refresh하는 메서드입니다. 이 메서드로 OauthToken을 유효한 상태로 유지할 수 있습니다.

**CommonAuthService**
해당 클래스는 카카오 로그인 사용자, 일반 로그인 사용자가 공통으로 사용하는 인증관련 로직을 작성한 것입니다.
공통 인증 사항은 다음과 같이 크게 8가지로 분류해 볼 수 있습니다.
- **reissue**: 서버에서 발급한 accessToken이 만료되면 해당 로직이 호출되어야 합니다. refreshToken을 POST로 전송하면, JwtTokenDto를 다시 생성하여 발급합니다. 이때 제출된 refreshToken은 <refreshToken, "Deprecated">로 redis에 저장되어 블랙리스트와 같은 효과로 만료시킵니다.
- **회원 탈퇴**: 아직은 단순히 해당 회원만 삭제하는 로직만 취하고 있으며, 추후 관련된 엔티티들을 추가로 삭제하는 로직으로 업데이트 예정입니다. 또한 회원이 탈퇴하면, 사용중이던 accessToken과 refreshToken을 만료시키는 작업을 수행합니다.
- **회원 정보 보기**: 해당 API를 호출하면, 이름, 이메일, 역할, 주소, 가입 날짜(createdAt)을 반환합니다.
- **회원 정보 수정**: 해당 API에서는 사용자의 이름, 역할, 주소만 바꿀 수 있도록 작성되었으며, PUT Method로 작성되어있습니다.
- **이메일 수정**: 이 API는 GeneralAuthService에 작성된 메일 인증 관련 메서드를 연계하여 사용하도록 설계되었으며, 인증이 완료된 email에 대해서만 변경이 가능하도록 작성되었습니다(PATCH). 또한, type이 KAKAO인 사용자, 즉 카카오 로그인 사용자가 해당 API를 호출하면 Exception을 터뜨리도록 작성되었습니다. 카카오 로그인 사용자는 카카오 서버가 제공하는 정보를 토대로 관리가 되는데, 이메일이 변경되면 정보 불일치로 인해 관리가 힘들어 지기 때문입니다.
- **비밀번호 검증**: 해당 API는 비밀번호 변경을 하기 전, 다시 한번 사용자 인증을 하는 작업으로, 비밀번호를 POST로 제출하도록 작성되었습니다. 해당 비밀번호가 일치하지 않으면 Exception을 터뜨리고, 일치하면 <"memberId+password", "verified">로 redis에 30분간 비밀번호가 검증되었다는 상태를 저장합니다.
- **비밀번호 변경**: 해당 API는 PATCH로 정의되어있으며, 위 비밀번호 검증으로 인증된 회원에 한에서만 비밀번호를 업데이트 합니다. 당연하게도 비밀번호 검증, 변경은 카카오 로그인 사용자가 접근하면 Exception을 터뜨리도록 작성하였습니다

**JwtToken의 흐름**:
- **로그인 시**: JwtTokenProvider를 통해 JwtTokenDto를 발급합니다. 이때 redis에 <refreshToken, memberId>를 refreshToken의 생명주기만큼 저장합니다. refreshToken에는 사용자의 어떠한 정보도 포함되지 않게 만들도록 작성했기 때문에, reissue에서 토큰 재발급 과정에서 필요한 회원 정보를 얻기 위함입니다.
- **reissue**: 사용자로부터 전달받은 refreshToken을 이용하여 redis에 저장된 memberId를 가져옵니다. 이후 새로운 JwtTokenDto를 생성하여 발급하고, 기존에 사용중이던 refreshToken을 <refreshToken, "Deprecated">로 저장하여 만료시킵니다.
- **로그아웃 시**: request body로 전달받은 refreshToken과 request header 로부터 가져온 accessToken을 <토큰, "Deprecated">로 각 토큰의 생명주기만큼 redis에 저장하여 만료시킵니다.
- **회원 탈퇴시**: 로그아웃과 로직이 거의 동일합니다. 다만 회원 삭제 로직이 추가된 것만 다릅니다.
- **accessToken으로 제한된 리소스에 접근시**: JwtFilter에서 헤더에 첨부된 accessToken을 가져오고, 해당 토큰이 redis에 "Deprecated"로 저장되어있는지 확인합니다. 즉 redis에 블랙리스트로 관리되는 토큰일 경우 AuthenticationEntryPoint로 처리되도록 하고, 유효할 경우 인증 및, 인가 처리를 해줍니다.
## Screenshots (Optional)
- JwtTokenDto:
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/e2a11de2-0077-4df1-a9fd-1c2054ff2661)
- grantType은 "Bearer"로 토큰 타입을 의미합니다.
- accessToken은 Jwt accessToken이 첨부됩니다.
- refreshToken은 accessToken을 reissue할 때 사용되는 refreshToken이 첨부됩니다.
- accessTokenExpiresIn은 해당 필드는 accessToken이 만료되는 시간을 long 타입으로 표현한 것이며, 구체적으로는 1970년 1월 1일 00:00:00 UTC(UNIX epoch time)부터 accessTokenExpiresIn까지의 시간을 밀리초로 표현한 값입니다.

- RedisTemplate
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/f560070b-f8d0-47ac-bbc3-db0ad9d4da23)
redisTemplate을 <String, Object>로 저장할 수 있도록 위 사진과 같이 설정하였습니다.

2023-09-18 09:13 UTC, dl-00-e8 requested changes
PR 설명과 함께 확인하니 더욱 파악하기 쉬웠습니다. 다만 일부 바꿔보면 어떨까 싶은 부분들이 있어서 해당 부분 확인해주시면 좋을 것 같습니다.

2023-09-18 09:13 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/controller/AuthController.java
AuthController에 다 모아놓기 보단, 같은 도메인인 member 패키지 안에서 AuthController와 MemberController를 분리하는 게 좋을 것 같습니다.

2023-09-18 09:13 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/dto/response/AuthMeRes.java
AuthMeRes라는 네이밍을 통해서 어떤 용도인지 파악하기가 조금 어려웠습니다. 조금 더 직관적인 네이밍으로 사용할 수 있는 것이 있을까요?

2023-09-18 09:13 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/repository/MemberRepository.java
커스터마이징한 JPA의 사용용도를 주석으로 달아준다면 가독성이 더 좋은 코드가 될 것 같습니다.

2023-09-19 03:50 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/controller/AuthController.java
넵! 말씀하신 부분을 고민해본 결과, 인증에 대한 controller와 회원 정보 수정과 같은 member에 대한 controller는 목적 상 분리하는것이 합리적이라고 생각이 들어, AuthController와 MemberController로 분리하였습니다.

### AuthController:
- 이메일 인증
- 회원가입
- 로그인
- 로그아웃
- reissue

### MemberController:
- 회원 탈퇴
- 회원 정보 보기
- 회원 정보 수정
- 이메일 수정
- 비밀번호 검증 및 수정

위와 같이 나누어서 작성하였습니다

2023-09-19 03:51 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/dto/response/AuthMeRes.java
네. 좋은 지적 감사합니다. 해당 DTO는 회원 정보를 담기 위한 Response DTO로써, 네이밍이 부적절하다는 것에 동의합니다.
따라서 MemberInfoRes라는 이름으로 변경하도록 하겠습니다.

2023-09-19 03:53 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/repository/MemberRepository.java
요청하신대로 MemberRepository에 작성된 메서드들의 쓰임새와 의도를 작성하여 남겼습니다. 감사합니다

2023-09-19 04:34 UTC, Cfctor9 approved these changes

2023-09-20 14:19 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/controller/AuthController.java
회원 가입이 auth에 있는데, 회원 탈퇴가 member에 있는 것이 약간 어색한데, 혹시 어떻게 생각하시나요?

2023-09-20 14:20 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/dto/response/AuthMeRes.java
직관적인 네이밍이 된 것 같습니다. 감사합니다.

2023-09-20 14:21 UTC, dl-00-e8 commented on src/main/java/com/KooKPaP/server/domain/member/repository/MemberRepository.java
네, 주석을 통해 사용용도를 확실하게 파악할 수 있는 것 같네요, 수고 많으셨습니다!

2023-09-20 14:22 UTC, dl-00-e8 approved these changes
회원탈퇴 API 위치가 어느 컨트롤러에 해당할지만 판단해서 답변 남겨주시면 될 것 같습니다. 나머지는 다 좋은 것 같습니다. 수고 많으셨습니다!

2023-09-21 09:12 UTC, Ryooon2 commented on src/main/java/com/KooKPaP/server/domain/member/controller/AuthController.java
넵 죄송합니다. 꼼꼼히 확인하지 못했네요.
바로 조치하였습니다

2023-09-21 09:13 UTC, merged